<a href="https://colab.research.google.com/github/Muqtarali/Machine-Learning/blob/main/%20Supervised%20Learning/Naive%20Bayes%20Classifier/Naive_Bayes_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
import numpy as np
import pandas as pd

In [37]:
df=pd.read_csv('/content/play_tennis.csv')

In [38]:
df.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [39]:
df.drop(columns=['day'],inplace=True)

In [40]:
df.head()

    outlook  temp humidity    wind play
0     Sunny   Hot     High    Weak   No
1     Sunny   Hot     High  Strong   No
2  Overcast   Hot     High    Weak  Yes
3      Rain  Mild     High    Weak  Yes
4      Rain  Cool   Normal    Weak  Yes

In [41]:
x=df.iloc[:,0:4]

In [42]:
x

     outlook  temp humidity    wind
0      Sunny   Hot     High    Weak
1      Sunny   Hot     High  Strong
2   Overcast   Hot     High    Weak
3       Rain  Mild     High    Weak
4       Rain  Cool   Normal    Weak
5       Rain  Cool   Normal  Strong
6   Overcast  Cool   Normal  Strong
7      Sunny  Mild     High    Weak
8      Sunny  Cool   Normal    Weak
9       Rain  Mild   Normal    Weak
10     Sunny  Mild   Normal  Strong
11  Overcast  Mild     High  Strong
12  Overcast   Hot   Normal    Weak
13      Rain  Mild     High  Strong

In [43]:
y=df.iloc[:,4]

In [44]:
y

0      No
1      No
2     Yes
3     Yes
4     Yes
5      No
6     Yes
7      No
8     Yes
9     Yes
10    Yes
11    Yes
12    Yes
13     No
Name: play, dtype: object

In [45]:
df['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [46]:
py=9/14
pn=5/14

In [47]:
#outlook
pd.crosstab(df['outlook'],df['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [48]:
pon=0
prn=2/5
psn=3/5

poy=4/9
pry=3/9
psy=2/9

In [49]:
pd.crosstab(df['temp'],df['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [50]:
pcoolno=1/5
pcoolyes=3/9

pHotno=2/5
pHotyes=2/9

pMildno=2/5
pMildyes=4/9

In [51]:
pd.crosstab(df['humidity'],df['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [53]:


pHighno=4/5
pHighyes=3/9

pNormalno=1/5
pNormalyes=6/9

In [54]:
pd.crosstab(df['wind'],df['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [56]:
pStrongno=3/5
pStrongyes=3/9

pWekno=2/5
pWeakyes=6/9

In [57]:
#problem 1
#oulook=sunny,temo=hot,humidity=high,wind=week
#play or not

pyes=py*psy*pHotyes*pHighyes*pWeakyes
print(pyes)

0.007054673721340388

In [59]:
# proballiyt for no
pno=pn*psn*pHotno*pHighno*pWekno
print(pno)

0.02742857142857143

In [ ]:
# result no play

In [60]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn import datasets

# 1. Load a sample dataset (Iris Dataset)
data = datasets.load_iris()
X = data.data
y = data.target

# 2. Split dataset into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 3. Initialize the Gaussian Naive Bayes Classifier
model = GaussianNB()

# 4. Train the model using the training data
model.fit(X_train, y_train)

# 5. Predict the labels for the test dataset
y_pred = model.predict(X_test)

# 6. Evaluate model performance
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy * 100:.2f}%\n")
print("Classification Report:")
print(classification_report(y_test, y_pred, target_names=data.target_names))

Model Accuracy: 100.00%

Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

In [61]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report
from sklearn import datasets

# 1. Load a sample dataset (Iris Dataset)
data = datasets.load_iris()
X = data.data
y = data.target

# 2. Split dataset into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 3. Initialize the Gaussian Naive Bayes Classifier
model = GaussianNB()

# 4. Train the model using the training data
model.fit(X_train, y_train)

# 5. Predict the labels for the test dataset
y_pred = model.predict(X_test)

# 6. Evaluate model performance
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy * 100:.2f}%\n")
print("Classification Report:")
print(classification_report(y_test, y_pred, target_names=data.target_names))

print("-" * 50)
print("=== SINGLE CUSTOM INPUT TEST ===")

# 7. Naya input data define karein (Format: [[sepal length, sepal width, petal length, petal width]])
# Aap in values ko apni pasand ke hisaab se change kar sakte hain
custom_input = np.array([[5.1, 3.5, 1.4, 0.2]])

# 8. Custom input ke liye prediction nikalein
predicted_class_id = model.predict(custom_input)[0]
predicted_class_name = data.target_names[predicted_class_id]

# 9. Har class ke liye probability check karein (Pata chalega model kitna confident hai)
prediction_probabilities = model.predict_proba(custom_input)[0]

# Results ko print karein
print(f"Custom Input Data: {custom_input[0]}")
print(f"Predicted Class ID: {predicted_class_id}")
print(f"Predicted Flower Species: {predicted_class_name.upper()}")
print("\nPrediction Confidence Probabilities:")
for name, prob in zip(data.target_names, prediction_probabilities):
    print(f" - {name.capitalize()}: {prob * 100:.2f}%")

Model Accuracy: 100.00%

Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

--------------------------------------------------
=== SINGLE CUSTOM INPUT TEST ===
Custom Input Data: [5.1 3.5 1.4 0.2]
Predicted Class ID: 0
Predicted Flower Species: SETOSA

Prediction Confidence Probabilities:
 - Setosa: 100.00%
 - Versicolor: 0.00%
 - Virginica: 0.00%