<a href="https://colab.research.google.com/github/Muqtarali/Machine-Learning/blob/main/Supervised%20Learning/Classification%20Metrics/Classification_Metrics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [141]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Load the dataset from the correct path
df = pd.read_csv('/content/heart.csv')
display(df.head())

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [142]:
from sklearn.model_selection import train_test_split

X = df.drop('target', axis=1)
y = df['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

In [143]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler

# Initialize StandardScaler
scaler = StandardScaler()

# Scale the training and testing features
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [144]:
lr=LogisticRegression(max_iter=1000) # Increased max_iter for better convergence
dt=DecisionTreeClassifier()

In [145]:
lr.fit(X_train_scaled,y_train)
dt.fit(X_train_scaled,y_train)

DecisionTreeClassifier()

In [146]:
y_pred1 = lr.predict(X_test_scaled)
y_pred2 = dt.predict(X_test_scaled)

In [147]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 0.8688524590163934
Accuracy of Decision Trees 0.8360655737704918

In [148]:
confusion_matrix(y_test,y_pred1)

array([[25,  7],
       [ 1, 28]])

# classification-metrics-multi for multi class\**bold text**

In [149]:

df1 = pd.read_csv('/content/Iris.csv')
df1.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [150]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df1['Species'] = encoder.fit_transform(df1['Species'])
df1.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        0
1   2            4.9           3.0            1.4           0.2        0
2   3            4.7           3.2            1.3           0.2        0
3   4            4.6           3.1            1.5           0.2        0
4   5            5.0           3.6            1.4           0.2        0

In [151]:
from sklearn.model_selection import train_test_split

# Correctly split features (X) and target (y) for df1, dropping the 'Id' column
X = df1.drop(['Id', 'Species'], axis=1)
y = df1['Species']

X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [152]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler # Import StandardScaler for Iris data

In [153]:
clf1 = LogisticRegression(max_iter=1000) # Increased max_iter for convergence
clf2 = DecisionTreeClassifier()

In [158]:
# Initialize StandardScaler for Iris data
scaler_iris = StandardScaler()

# Scale the training and testing features for Iris
X_train_scaled_iris = scaler_iris.fit_transform(X_train)
X_test_scaled_iris = scaler_iris.transform(X_test)

clf1.fit(X_train_scaled_iris,y_train)
clf2.fit(X_train_scaled_iris,y_train)

DecisionTreeClassifier()

In [159]:
y_pred_mul=clf1.predict(X_test_scaled_iris)
y_pred1_mul=clf2.predict(X_test_scaled_iris)

In [160]:
from sklearn.metrics import accuracy_score,confusion_matrix
print(accuracy_score(y_test,y_pred_mul))
print(accuracy_score(y_test,y_pred1_mul))

0.9666666666666667
0.9666666666666667

In [161]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1_mul),columns=list(range(0,3)))

Logistic Regression Confusion Matrix

    0   1  2
0  11   0  0
1   0  12  1
2   0   0  6